import "./globals.css";
import Navbar from "../components/navbar";
import SessionWrapper from "@/components/sessionWrapper";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` min-h-screen flex flex-col`}>
        <SessionWrapper>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </ThemeProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
